### ISSUE TITLE
Disallow this.state inside setState

### ISSUE THREAD

**Issue by janowsiany** [vazco/eslint-plugin-vazco#3]
I came up with an idea that we could implement this rule.

```js
// BAD
this.setState({count: state.count + 1});

//GOOD
this.setState(prevState => ({count: prevState.count + 1}));
```

**Comment by radekmie** [comment]
It's already doable with [`eslint-plugin-react`](https://github.com/yannickcr/eslint-plugin-react), using [`react/no-access-state-in-setstate`](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-access-state-in-setstate.md) rule.
